apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Wildfly Application Server with PostgreSQL config
    iconClass: icon-wildfly
    openshift.io/display-name: Custom WildFly
    openshift.io/provider-display-name: shaped.ch
    supports: eap,jee,java,jboss,xpaas
    tags: wildfly
  name: wildfly-postgresql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=${APPLICATION_NAME}
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ENVIRONMENT
            value: ${ENVIRONMENT}
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: POSTGRES_HOST
            value: ${POSTGRES_HOST}
          - name: POSTGRES_USER
            value: ${POSTGRES_USER}
          - name: POSTGRES_PASSWORD
            value: ${POSTGRES_PASSWORD}
          image: ${WILDFLY_IMAGE}
          livenessProbe:
            exec:
              command: 
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command: 
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
          securityContext:
            privileged: false
        terminationGracePeriodSeconds: 60
    triggers:
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
- description: Wildfly container image to be used
  displayName: Wildfly container image
  name: WILDFLY_IMAGE
  required: true
  value: docker.io/openshift/wildfly-160-centos7:latest
- description: Runtime Environment name
  displayName: Environment
  name: ENVIRONMENT
  required: true
  value: development
- description: Java options
  displayName: Java opts
  name: JAVA_OPTS
  required: false
- description: Postgres connection username
  displayName: DB user
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: POSTGRES_USER
  required: true
- description: Postgres connection password
  displayName: DB password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: POSTGRES_PASSWORD
  required: true
- description: Specify hostname of the database
  displayName: DB hostname
  name: POSTGRES_HOST
  required: true
  value: db
