# Secure Demo Application
# ----------------
# * http://hostname:11000/app: LoadBalanced SystemInfo (Container 1 & 2)
# * http://hostname:11000/node1: SystemInfo Container 1
# * http://hostname:11000/node2: SystemInfo Container 2
# * http://hostname:11000/: LoadBalanced Apache HTTPD (Directory ./website)
# * http://hostname:11000/site1: Apache HTTPD Container 1
# * http://hostname:11000/site2: Apache HTTPD Container 2
# *
# * node1 should be accessible directly as http://hostname:11001
# * node1 should have 2GB Heap-Space
#
# SystemInfo Container: christofluethi/systeminfo:1.0.0
# Apache Httpd: httpd:2.4
# Apache Httpd: centos/httpd-24-centos7
# nginx: nginx:1.15.8
# nginx: nginxinc/nginx-unprivileged:1.15.8
#
version: '3'
services:
  proxy:
    user: "1001:1001"
    image: nginxinc/nginx-unprivileged:1.15.8
    hostname: proxy
    restart: "no"
    networks:
    - front
    - app
    - website
    ports:
    - 11000:8080
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:Z
    depends_on:
    - systeminfo1
    - systeminfo2
    - website1
    - website2

  systeminfo1:
    user: "1000:1000"
    image: christofluethi/systeminfo:1.0.0
    hostname: systeminfo1
    restart: "no"
    networks:
    - app
    environment:
    - JAVA_OPTS=-Xmx2048m -Xms512m
    ports:
    - 11001:8080

  systeminfo2:
    user: "1000:1000"
    image: christofluethi/systeminfo:1.0.0
    hostname: systeminfo2
    restart: "no"
    networks:
    - app

  website1:
    user: "1001:1001"
    image: centos/httpd-24-centos7
    hostname: website
    restart: "no"
    networks:
    - website
    volumes:
    - ./website:/usr/local/apache2/htdocs:z

  website2:
    user: "1001:1001"
    image: centos/httpd-24-centos7
    hostname: website
    restart: "no"
    networks:
    - website
    volumes:
    - ./website:/usr/local/apache2/htdocs:z

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.227.0/24
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.228.0/24
  website:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.0/24

